export const RAB_STATUS = {
    WAITING_FOR_COORDINATOR: "WAITING_FOR_COORDINATOR",
    WAITING_FOR_MANAGER: "WAITING_FOR_MANAGER",
    APPROVED: "APPROVED",
    REJECTED_BY_COORDINATOR: "REJECTED_BY_COORDINATOR",
    REJECTED_BY_MANAGER: "REJECTED_BY_MANAGER",
    REJECTED_BY_DIREKTUR: "REJECTED_BY_DIREKTUR"
} as const;

export type RabStatus = (typeof RAB_STATUS)[keyof typeof RAB_STATUS];

export const ACTIVE_RAB_STATUSES: RabStatus[] = [
    RAB_STATUS.WAITING_FOR_COORDINATOR,
    RAB_STATUS.WAITING_FOR_MANAGER,
    RAB_STATUS.APPROVED
];
