export const DC_PROJECT_STATUS = {
    PROJECT_CREATED: "PROJECT_CREATED",
    SOIL_TENDER: "SOIL_TENDER",
    SOIL_WORK_RESULT: "SOIL_WORK_RESULT",
    PLANNER_TENDER: "PLANNER_TENDER",
    MK_TENDER: "MK_TENDER",
    CONTRACTOR_TENDER: "CONTRACTOR_TENDER",
    CONSTRUCTION_MONITORING: "CONSTRUCTION_MONITORING",
    SAT_SUPERVISION: "SAT_SUPERVISION",
    BAST_PREPARATION: "BAST_PREPARATION",
    BAST_APPROVAL: "BAST_APPROVAL",
    FINAL_TERM_BILLING: "FINAL_TERM_BILLING",
    COMPLETED: "COMPLETED"
} as const;

export const DC_PROJECT_STAGE_SEQUENCE = [
    DC_PROJECT_STATUS.PROJECT_CREATED,
    DC_PROJECT_STATUS.SOIL_TENDER,
    DC_PROJECT_STATUS.SOIL_WORK_RESULT,
    DC_PROJECT_STATUS.PLANNER_TENDER,
    DC_PROJECT_STATUS.MK_TENDER,
    DC_PROJECT_STATUS.CONTRACTOR_TENDER,
    DC_PROJECT_STATUS.CONSTRUCTION_MONITORING,
    DC_PROJECT_STATUS.SAT_SUPERVISION,
    DC_PROJECT_STATUS.BAST_PREPARATION,
    DC_PROJECT_STATUS.BAST_APPROVAL,
    DC_PROJECT_STATUS.FINAL_TERM_BILLING,
    DC_PROJECT_STATUS.COMPLETED
] as const;

export const DC_TENDER_TYPE = {
    SOIL_INVESTIGATION: "SOIL_INVESTIGATION",
    PLANNER: "PLANNER",
    SUPERVISOR_MK: "SUPERVISOR_MK",
    CONTRACTOR: "CONTRACTOR"
} as const;

export const DC_VENDOR_SERVICE_TYPES = Object.values(DC_TENDER_TYPE);

export const DC_TENDER_STATUS = {
    DRAFT: "DRAFT",
    INVITATION_SENT: "INVITATION_SENT",
    QUALIFICATION_REVIEW: "QUALIFICATION_REVIEW",
    QUALIFIED_PARTICIPANTS_SELECTED: "QUALIFIED_PARTICIPANTS_SELECTED",
    TENDER_OPEN: "TENDER_OPEN",
    TENDER_CLOSED: "TENDER_CLOSED",
    PRICE_REVIEW: "PRICE_REVIEW",
    WINNER_REVIEW: "WINNER_REVIEW",
    AWARDED: "AWARDED",
    CONTRACT_ISSUED: "CONTRACT_ISSUED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED"
} as const;

export const DC_APPROVAL_STATUS = {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    REVISION_REQUESTED: "REVISION_REQUESTED"
} as const;

export const DC_ROLES = {
    SOIL_CONSULTANT: "KONSULTAN SOIL INVESTIGATION",
    PLANNER_CONSULTANT: "KONSULTAN PERENCANA",
    SUPERVISOR_MK: "KONSULTAN PENGAWAS DC",
    CONTRACTOR: "KONTRAKTOR DC",
    DC_MANAGER: "DC BUILDING & DEVELOPMENT MANAGER",
    DC_SPECIALIST: "DC BUILDING & DEVELOPMENT SPECIALIST",
    BUILDING_DEVELOPMENT_GM: "BUILDING & DEVELOPMENT GENERAL MANAGER",
    LOCATION_DEVELOPMENT_GM: "LOCATION & DEVELOPMENT GENERAL MANAGER",
    PROPERTY_DEVELOPMENT_DIRECTOR: "PROPERTY DEVELOPMENT DIRECTOR",
    SUPER_HUMAN: "BUILDING & MAINTENANCE SUPER HUMAN"
} as const;

export type DcProjectStatus = (typeof DC_PROJECT_STATUS)[keyof typeof DC_PROJECT_STATUS];
export type DcTenderType = (typeof DC_TENDER_TYPE)[keyof typeof DC_TENDER_TYPE];
