// Scope filters are generated by the repository; group only rows already visible to the actor.
export function rabApprovalNotificationSql(branchWhere: string, companyWhere: string, limitParameter: number) {
 return `WITH eligible AS (
 SELECT r.id, r.id_toko, r.created_at, r.status, r.nama_pt, t.nama_toko,
 t.nomor_ulok, t.lingkup_pekerjaan, t.cabang, t.proyek
 FROM rab r JOIN toko t ON t.id=r.id_toko
 WHERE r.status=ANY($1::text[]) ${branchWhere} ${companyWhere}
 ), paired AS (
 SELECT *, count(*) OVER matching AS member_count,
 count(*) FILTER (WHERE upper(trim(lingkup_pekerjaan))='SIPIL') OVER matching AS sipil_count,
 count(*) FILTER (WHERE upper(trim(lingkup_pekerjaan))='ME') OVER matching AS me_count,
 min(id) FILTER (WHERE upper(trim(lingkup_pekerjaan))='SIPIL') OVER matching AS sipil_id
 FROM eligible WINDOW matching AS (PARTITION BY nomor_ulok, upper(trim(cabang)), upper(trim(coalesce(proyek,''))), upper(trim(coalesce(nama_pt,''))), status)
 ), labeled AS (
 SELECT *, (member_count=2 AND sipil_count=1 AND me_count=1 AND coalesce(trim(nomor_ulok),'')<>'') AS combined
 FROM paired
 ), canonical AS (
 SELECT DISTINCT ON (CASE WHEN combined THEN sipil_id ELSE id END) *
 FROM labeled ORDER BY CASE WHEN combined THEN sipil_id ELSE id END,
 CASE WHEN upper(trim(lingkup_pekerjaan))='SIPIL' THEN 0 ELSE 1 END
 )
 SELECT 'RAB' AS entity_type,id AS entity_id,id_toko,coalesce(nama_toko,nomor_ulok) AS title,
 nomor_ulok,CASE WHEN combined THEN 'SIPIL + ME' ELSE lingkup_pekerjaan END AS lingkup_pekerjaan,cabang,nama_pt,status,
 CASE WHEN combined THEN 'Approval RAB berlaku untuk SIPIL dan ME.' ELSE 'RAB menunggu approval sesuai role Anda.' END AS description,
 'Buka Approval RAB' AS action_label,'/approval?type=RAB&id='||id AS action_url,
 count(*) OVER() AS total_count
 FROM canonical ORDER BY created_at DESC,id DESC LIMIT $${limitParameter}`;
}
