ALTER TABLE rab
  ADD COLUMN IF NOT EXISTS beanspot_type VARCHAR(20),
  ADD COLUMN IF NOT EXISTS is_hth BOOLEAN,
  ADD COLUMN IF NOT EXISTS hth_meter NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS is_fasade BOOLEAN;
