-- Name: denda_keterlambatan_action; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.denda_keterlambatan_action (
    id bigint NOT NULL,
    id_toko integer,
    id_opname_final integer,
    nomor_ulok text,
    lingkup_pekerjaan text,
    cabang text,
    action_type text NOT NULL,
    status text DEFAULT 'WAITING_MANAGER'::text NOT NULL,
    hari_denda integer NOT NULL,
    nilai_denda numeric DEFAULT 0 NOT NULL,
    catatan text,
    link_pdf text,
    actor_email text,
    actor_role text,
    created_at timestamp without time zone DEFAULT timezone('Asia/Jakarta'::text, now()) NOT NULL,
    updated_at timestamp without time zone DEFAULT timezone('Asia/Jakarta'::text, now()) NOT NULL,
    sp_level integer,
    instruksi_tindak_lanjut text,
    deadline_tindak_lanjut date,
    lampiran_1_url text,
    lampiran_2_url text,
    nomor_surat text,
    submitted_by_email text,
    submitted_by_role text,
    submitted_at timestamp without time zone,
    manager_approved_by text,
    manager_approved_role text,
    manager_approved_at timestamp without time zone,
    manager_rejected_by text,
    manager_rejected_role text,
    manager_rejected_at timestamp without time zone,
    manager_rejected_reason text,
    sent_to_contractor_at timestamp without time zone,
    viewed_by_contractor_at timestamp without time zone,
    acknowledged_by_contractor_at timestamp without time zone,
    expires_at timestamp without time zone,
    nama_kontraktor text,
    nomor_spk text,
    alasan_sp text,
    acknowledged_by_email text,
    acknowledged_by_role text,
    catatan_acknowledge text,
    alasan_lainnya text,
    submitted_by_name text,
    nama_toko text,
    kode_toko text
);

