-- Name: projek_planning; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projek_planning (
    id integer NOT NULL,
    id_toko integer NOT NULL,
    nomor_ulok character varying(100) NOT NULL,
    email_pembuat character varying(255) NOT NULL,
    nama_toko character varying(255),
    kode_toko character varying(50),
    cabang character varying(100),
    proyek character varying(255),
    lingkup_pekerjaan character varying(100),
    jenis_proyek character varying(100),
    estimasi_biaya numeric(15,2),
    keterangan text,
    nama_pengaju character varying(255),
    nama_lokasi character varying(255),
    jenis_pengajuan character varying(100),
    jenis_pengajuan_lainnya character varying(255),
    link_fpd text,
    link_rab text,
    link_gambar_kerja text,
    link_desain_3d text,
    link_fpd_approved text,
    status character varying(50) DEFAULT 'DRAFT'::character varying NOT NULL,
    butuh_desain_3d boolean DEFAULT false NOT NULL,
    bm_approver_email character varying(255),
    bm_waktu_persetujuan timestamp without time zone,
    bm_alasan_penolakan text,
    pp1_approver_email character varying(255),
    pp1_waktu_persetujuan timestamp without time zone,
    pp1_alasan_penolakan text,
    pp_manager_approver_email character varying(255),
    pp_manager_waktu_persetujuan timestamp without time zone,
    pp_manager_alasan_penolakan text,
    pp2_approver_email character varying(255),
    pp2_waktu_persetujuan timestamp without time zone,
    pp2_alasan_penolakan text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_ruko boolean DEFAULT false,
    jumlah_lantai integer,
    link_gambar_kompetitor text,
    link_rab_sipil character varying(2048),
    link_rab_me character varying(2048),
    is_head_to_head boolean DEFAULT false NOT NULL,
    is_seating_area boolean DEFAULT false NOT NULL,
    is_dark_store boolean DEFAULT false NOT NULL,
    beanspot_tipe character varying(100),
    link_gambar_kerja_final_sipil text,
    link_gambar_kerja_final_me text,
    alamat_toko text,
    link_google_maps text,
    link_pdf text,
    link_siteplan text,
    luas_bangunan character varying(100) DEFAULT NULL::character varying,
    luas_area_terbuka character varying(100) DEFAULT NULL::character varying,
    luas_area_terbangun character varying(100) DEFAULT NULL::character varying,
    luas_gudang character varying(100) DEFAULT NULL::character varying,
    luas_area_parkir character varying(100) DEFAULT NULL::character varying,
    luas_area_sales character varying(100) DEFAULT NULL::character varying,
    pxl_bangunan character varying(100) DEFAULT NULL::character varying,
    pxl_area_parkir character varying(100) DEFAULT NULL::character varying,
    jarak_head_to_head character varying(50) DEFAULT NULL::character varying,
    id_rab_sipil integer,
    id_rab_me integer,
    bm2_approver_email character varying(255) DEFAULT NULL::character varying,
    bm2_waktu_persetujuan timestamp without time zone,
    bm2_alasan_penolakan text,
    pp2_rab_status character varying(20) DEFAULT NULL::character varying,
    pp2_gambar_status character varying(20) DEFAULT NULL::character varying,
    pp2_rab_rejected_item_ids integer[],
    pp2_rab_rejected_item_notes text,
    pp_manager_rab_status character varying(20) DEFAULT NULL::character varying,
    pp_manager_gambar_status character varying(20) DEFAULT NULL::character varying,
    pp_manager_rab_rejected_item_ids integer[],
    pp_manager_rab_rejected_item_notes text,
    p_bangunan numeric(15,2) DEFAULT NULL::numeric,
    l_bangunan numeric(15,2) DEFAULT NULL::numeric,
    p_area_parkir numeric(15,2) DEFAULT NULL::numeric,
    l_area_parkir numeric(15,2) DEFAULT NULL::numeric,
    jumlah_ac integer,
    pk_ac numeric(10,2) DEFAULT NULL::numeric,
    listrik_va integer,
    listrik_phase integer,
    sumber_air_bersih character varying(100) DEFAULT NULL::character varying,
    drainase_air_kotor character varying(100) DEFAULT NULL::character varying,
    akhir_masa_sewa date,
    spd numeric,
    link_ba_tidak_sesuai_standar text,
    bm_regional_approver_email character varying(255) DEFAULT NULL::character varying,
    bm_regional_waktu_persetujuan timestamp without time zone,
    bm_regional_alasan_penolakan text,
    bm_regional_rab_status character varying(20),
    bm_regional_gambar_status character varying(20),
    bm_regional_rab_rejected_item_ids integer[],
    bm_regional_rab_rejected_item_notes text
);

