-- Name: rab; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rab (
    id integer NOT NULL,
    id_toko integer,
    status character varying(255),
    nama_pt character varying(255),
    link_pdf_gabungan character varying(255),
    link_pdf_non_sbo character varying(255),
    link_pdf_rekapitulasi character varying(255),
    logo text,
    email_pembuat character varying(255),
    pemberi_persetujuan_direktur character varying(255),
    waktu_persetujuan_direktur timestamp without time zone,
    pemberi_persetujuan_koordinator character varying(255),
    waktu_persetujuan_koordinator timestamp without time zone,
    pemberi_persetujuan_manager character varying(255),
    waktu_persetujuan_manager timestamp without time zone,
    alasan_penolakan character varying(255),
    durasi_pekerjaan character varying(255),
    kategori_lokasi character varying(255),
    luas_bangunan character varying(255),
    luas_terbangun character varying(255),
    luas_area_terbuka character varying(255),
    luas_area_parkir character varying(255),
    luas_area_sales character varying(255),
    luas_gudang character varying(255),
    grand_total character varying(255),
    grand_total_non_sbo character varying(255),
    grand_total_final character varying(255),
    created_at timestamp without time zone DEFAULT timezone('Asia/Jakarta'::text, now()),
    link_pdf_sph character varying(255),
    waktu_penolakan timestamp without time zone,
    no_sph character varying(255),
    no_polis character varying(255),
    berlaku_polis character varying(255),
    file_asuransi text,
    ditolak_oleh character varying(255) DEFAULT 'NULL'::character varying,
    nama_persetujuan_koordinator character varying(255),
    nama_persetujuan_manager character varying(255),
    nama_persetujuan_direktur character varying(255),
    catatan_persetujuan_koordinator text,
    catatan_persetujuan_manager text,
    catatan_persetujuan_direktur text,
    catatan_penolakan text,
    link_pdf_materai text,
    projek_planning_id integer,
    beanspot_type character varying(20),
    is_hth boolean,
    hth_meter numeric(10,2),
    is_fasade boolean
);

